server:
  port: 9000
spring:
  application:
    name: backend-auth
  datasource:
    url: "jdbc:postgresql://localhost:5432/spring_auth_server"
    username: "jibesh"
    password: "password"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: TRACE